"""Golden-portfolio validation.

Heimdall's metrics are checked against an **independent implementation** written
here in plain Python — `statistics` and `math`, no NumPy, no SciPy, and no
application code. If both agree, the same mistake would have had to be made twice
in two different styles.

The dataset is `fixtures/market_data_golden/`: two instruments, 60 consecutive
weekdays, daily returns from a short repeating cycle. It is regenerated by
`scripts/generate_golden_fixtures.py` and committed, so the expected values never
move.

**Tolerances.** The independent implementation uses Python floats in a different
order of operations from NumPy's vectorized reductions, so the two differ in the
last few bits. A relative tolerance of 1e-9 is far tighter than any floating-point
discrepancy yet loose enough to be stable across platforms; an actual formula
error would be off by percent, not by 1e-9.
"""

from __future__ import annotations

import csv
import math
import statistics
from datetime import date
from pathlib import Path

import pytest

from app.analytics import calculations as calc

GOLDEN = Path(__file__).resolve().parent.parent.parent / "fixtures" / "market_data_golden"
RELATIVE_TOLERANCE = 1e-9

# The golden portfolio: 100 units of GLDA and 20 units of GLDB.
GOLDEN_QUANTITIES = {"GLDA": 100.0, "GLDB": 20.0}


def _read(symbol: str) -> list[tuple[date, float]]:
    """Read one golden series as (date, adjusted close)."""
    rows = []
    with (GOLDEN / f"{symbol}.csv").open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            rows.append((date.fromisoformat(row["date"]), float(row["adjusted_close"])))
    return rows


# --- Independent implementations ----------------------------------------------


def independent_returns(prices: list[float]) -> list[float]:
    """Simple returns, computed one at a time."""
    return [prices[index] / prices[index - 1] - 1.0 for index in range(1, len(prices))]


def independent_cumulative(returns: list[float]) -> float:
    """Compound returns with a plain loop."""
    total = 1.0
    for value in returns:
        total *= 1.0 + value
    return total - 1.0


def independent_annualized(returns: list[float], periods: int = 252) -> float:
    """Geometric annualization."""
    return (1.0 + independent_cumulative(returns)) ** (periods / len(returns)) - 1.0


def independent_volatility(returns: list[float], periods: int = 252) -> float:
    """Sample standard deviation, annualized."""
    return statistics.stdev(returns) * math.sqrt(periods)


def independent_sharpe(returns: list[float], annual_rate: float, periods: int = 252) -> float:
    """Sharpe ratio with a geometrically de-annualized risk-free rate."""
    periodic = (1.0 + annual_rate) ** (1.0 / periods) - 1.0
    excess = [value - periodic for value in returns]
    return statistics.fmean(excess) / statistics.stdev(excess) * math.sqrt(periods)


def independent_max_drawdown(values: list[float]) -> float:
    """Worst peak-to-trough decline, tracked with a running peak."""
    peak = values[0]
    worst = 0.0
    for value in values:
        peak = max(peak, value)
        worst = min(worst, value / peak - 1.0)
    return worst


def independent_quantile(values: list[float], probability: float) -> float:
    """Linear-interpolation quantile, matching NumPy's default method."""
    ordered = sorted(values)
    position = probability * (len(ordered) - 1)
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return ordered[int(position)]
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def independent_historical_var(returns: list[float], confidence: float, value: float) -> float:
    """VaR as a positive loss amount."""
    return max(-independent_quantile(returns, 1.0 - confidence) * value, 0.0)


def independent_expected_shortfall(
    returns: list[float],
    confidence: float,
    value: float,
) -> float:
    """Mean of the loss tail, as a positive amount."""
    threshold = independent_quantile(returns, 1.0 - confidence)
    tail = [item for item in returns if item <= threshold]
    return max(-statistics.fmean(tail) * value, 0.0)


def independent_covariance(first: list[float], second: list[float]) -> float:
    """Sample covariance from the definition."""
    mean_first = statistics.fmean(first)
    mean_second = statistics.fmean(second)
    products = [(a - mean_first) * (b - mean_second) for a, b in zip(first, second, strict=True)]
    return sum(products) / (len(first) - 1)


def independent_correlation(first: list[float], second: list[float]) -> float:
    """Pearson correlation from the definition."""
    return independent_covariance(first, second) / (
        statistics.stdev(first) * statistics.stdev(second)
    )


# --- Fixtures -----------------------------------------------------------------


@pytest.fixture(scope="module")
def golden():
    """The golden dataset, with weights and the independent return series."""
    series = {symbol: _read(symbol) for symbol in GOLDEN_QUANTITIES}
    prices = {symbol: [price for _, price in rows] for symbol, rows in series.items()}
    returns = {symbol: independent_returns(values) for symbol, values in prices.items()}

    values = {
        symbol: GOLDEN_QUANTITIES[symbol] * prices[symbol][-1] for symbol in GOLDEN_QUANTITIES
    }
    total = sum(values.values())
    weights = {symbol: value / total for symbol, value in values.items()}

    symbols = sorted(GOLDEN_QUANTITIES)
    portfolio = [
        sum(weights[symbol] * returns[symbol][index] for symbol in symbols)
        for index in range(len(returns[symbols[0]]))
    ]

    return {
        "series": series,
        "prices": prices,
        "returns": returns,
        "weights": weights,
        "symbols": symbols,
        "portfolio_returns": portfolio,
        "total_value": total,
    }


# --- Shape --------------------------------------------------------------------


def test_the_golden_dataset_has_the_expected_shape(golden):
    assert golden["symbols"] == ["GLDA", "GLDB"]
    assert len(golden["prices"]["GLDA"]) == 60
    assert len(golden["prices"]["GLDB"]) == 60
    assert len(golden["portfolio_returns"]) == 59


def test_the_golden_series_start_at_their_documented_prices(golden):
    assert golden["prices"]["GLDA"][0] == 100.0
    assert golden["prices"]["GLDB"][0] == 200.0


def test_weights_sum_to_one(golden):
    assert sum(golden["weights"].values()) == pytest.approx(1.0, rel=1e-15)


# --- Returns ------------------------------------------------------------------


def test_asset_returns_match_the_independent_calculation(golden):
    for symbol in golden["symbols"]:
        computed = calc.simple_returns(golden["prices"][symbol])
        assert computed == pytest.approx(golden["returns"][symbol], rel=RELATIVE_TOLERANCE)


def test_the_first_golden_return_is_exactly_two_percent(golden):
    """100 -> 102 by construction, so this one is checkable by eye."""
    assert golden["returns"]["GLDA"][0] == pytest.approx(0.02, abs=1e-12)


def test_portfolio_returns_match_the_independent_calculation(golden):
    weights = [golden["weights"][symbol] for symbol in golden["symbols"]]
    matrix = list(zip(*[golden["returns"][symbol] for symbol in golden["symbols"]], strict=True))

    computed = calc.portfolio_returns(weights, matrix)

    assert computed == pytest.approx(golden["portfolio_returns"], rel=RELATIVE_TOLERANCE)


def test_total_return_matches_the_independent_calculation(golden):
    expected = independent_cumulative(golden["portfolio_returns"])

    assert calc.cumulative_return(golden["portfolio_returns"]) == pytest.approx(
        expected, rel=RELATIVE_TOLERANCE
    )


def test_annualized_return_matches_the_independent_calculation(golden):
    expected = independent_annualized(golden["portfolio_returns"])

    assert calc.annualized_return(golden["portfolio_returns"]) == pytest.approx(
        expected, rel=RELATIVE_TOLERANCE
    )


# --- Risk ---------------------------------------------------------------------


def test_annualized_volatility_matches_the_independent_calculation(golden):
    expected = independent_volatility(golden["portfolio_returns"])

    assert calc.volatility(golden["portfolio_returns"]) == pytest.approx(
        expected, rel=RELATIVE_TOLERANCE
    )


def test_daily_volatility_matches_the_independent_calculation(golden):
    expected = statistics.stdev(golden["portfolio_returns"])

    assert calc.volatility(golden["portfolio_returns"], annualize=False) == pytest.approx(
        expected, rel=RELATIVE_TOLERANCE
    )


@pytest.mark.parametrize("annual_rate", [0.0, 0.02, 0.045])
def test_sharpe_ratio_matches_the_independent_calculation(golden, annual_rate):
    expected = independent_sharpe(golden["portfolio_returns"], annual_rate)

    assert calc.sharpe_ratio(
        golden["portfolio_returns"], annual_risk_free_rate=annual_rate
    ) == pytest.approx(expected, rel=RELATIVE_TOLERANCE)


def test_max_drawdown_matches_the_independent_calculation(golden):
    path = calc.value_history(golden["portfolio_returns"], starting_value=100_000.0)
    expected = independent_max_drawdown(list(path))

    assert calc.max_drawdown(path).drawdown == pytest.approx(expected, rel=RELATIVE_TOLERANCE)


def test_the_golden_portfolio_has_a_real_drawdown(golden):
    """A dataset with no drawdown would not exercise the calculation."""
    path = calc.value_history(golden["portfolio_returns"], starting_value=100_000.0)

    assert calc.max_drawdown(path).drawdown < -0.001


@pytest.mark.parametrize("confidence", [0.90, 0.95, 0.99])
def test_historical_var_matches_the_independent_calculation(golden, confidence):
    expected = independent_historical_var(golden["portfolio_returns"], confidence, 100_000.0)

    assert calc.historical_var(
        golden["portfolio_returns"],
        confidence=confidence,
        portfolio_value=100_000.0,
    ) == pytest.approx(expected, rel=RELATIVE_TOLERANCE)


@pytest.mark.parametrize("confidence", [0.90, 0.95, 0.99])
def test_expected_shortfall_matches_the_independent_calculation(golden, confidence):
    expected = independent_expected_shortfall(golden["portfolio_returns"], confidence, 100_000.0)

    assert calc.expected_shortfall(
        golden["portfolio_returns"],
        confidence=confidence,
        portfolio_value=100_000.0,
    ) == pytest.approx(expected, rel=RELATIVE_TOLERANCE)


def test_expected_shortfall_is_at_least_var_on_the_golden_data(golden):
    var = calc.historical_var(
        golden["portfolio_returns"], confidence=0.95, portfolio_value=100_000.0
    )
    shortfall = calc.expected_shortfall(
        golden["portfolio_returns"], confidence=0.95, portfolio_value=100_000.0
    )

    assert shortfall >= var


def test_parametric_var_matches_the_independent_calculation(golden):
    from scipy import stats

    returns = golden["portfolio_returns"]
    mean = statistics.fmean(returns)
    deviation = statistics.stdev(returns)
    expected = max(-(mean + float(stats.norm.ppf(0.05)) * deviation) * 100_000.0, 0.0)

    assert calc.parametric_var(
        returns, confidence=0.95, portfolio_value=100_000.0
    ) == pytest.approx(expected, rel=1e-8)


# --- Covariance and attribution ----------------------------------------------


def test_covariance_matches_the_independent_calculation(golden):
    first = golden["returns"]["GLDA"]
    second = golden["returns"]["GLDB"]
    matrix = list(zip(first, second, strict=True))

    covariance = calc.covariance_matrix(matrix, annualize=False)

    assert covariance[0][0] == pytest.approx(
        independent_covariance(first, first), rel=RELATIVE_TOLERANCE
    )
    assert covariance[0][1] == pytest.approx(
        independent_covariance(first, second), rel=RELATIVE_TOLERANCE
    )
    assert covariance[1][1] == pytest.approx(
        independent_covariance(second, second), rel=RELATIVE_TOLERANCE
    )


def test_correlation_matches_the_independent_calculation(golden):
    first = golden["returns"]["GLDA"]
    second = golden["returns"]["GLDB"]
    matrix = list(zip(first, second, strict=True))

    correlation = calc.correlation_matrix(matrix)

    assert correlation[0][1] == pytest.approx(
        independent_correlation(first, second), rel=RELATIVE_TOLERANCE
    )


def test_portfolio_volatility_from_covariance_matches_the_return_series(golden):
    """Two routes to the same number: the return series, and w' * C * w."""
    weights = [golden["weights"][symbol] for symbol in golden["symbols"]]
    matrix = list(zip(*[golden["returns"][symbol] for symbol in golden["symbols"]], strict=True))

    from_series = calc.volatility(golden["portfolio_returns"], annualize=False)
    from_covariance = calc.portfolio_volatility_from_covariance(
        weights,
        calc.covariance_matrix(matrix, annualize=False),
    )

    assert from_covariance == pytest.approx(from_series, rel=1e-9)


def test_risk_contributions_reconcile_on_the_golden_data(golden):
    weights = [golden["weights"][symbol] for symbol in golden["symbols"]]
    matrix = list(zip(*[golden["returns"][symbol] for symbol in golden["symbols"]], strict=True))
    covariance = calc.covariance_matrix(matrix)

    total = calc.portfolio_volatility_from_covariance(weights, covariance)
    contributions = calc.risk_contributions(weights, covariance)

    assert sum(item.component for item in contributions) == pytest.approx(total, rel=1e-12)
    assert sum(item.share for item in contributions) == pytest.approx(1.0, rel=1e-12)


def test_the_negatively_correlated_asset_reduces_total_risk(golden):
    """GLDB moves against GLDA, so its component contribution is negative.

    A diversifying holding genuinely lowers portfolio volatility; the attribution
    must show that rather than clamping every contribution to be positive.
    """
    weights = [golden["weights"][symbol] for symbol in golden["symbols"]]
    matrix = list(zip(*[golden["returns"][symbol] for symbol in golden["symbols"]], strict=True))
    contributions = calc.risk_contributions(weights, calc.covariance_matrix(matrix))

    assert contributions[0].share > contributions[1].share


# --- Documented reference values ----------------------------------------------


def test_documented_reference_values(golden):
    """Values quoted in docs/financial-methodology.md.

    If a calculation changes, this test fails and the documentation must be
    updated in the same commit.
    """
    returns = golden["portfolio_returns"]
    path = calc.value_history(returns, starting_value=100_000.0)

    assert round(golden["weights"]["GLDA"], 6) == 0.713699
    assert round(golden["weights"]["GLDB"], 6) == 0.286301

    assert round(calc.cumulative_return(returns), 6) == 0.059549
    assert round(calc.annualized_return(returns), 6) == 0.280254
    assert round(calc.volatility(returns, annualize=False), 6) == 0.013319
    assert round(calc.volatility(returns), 6) == 0.211435
    assert round(calc.sharpe_ratio(returns), 6) == 1.272574
    assert round(calc.sharpe_ratio(returns, annual_risk_free_rate=0.045), 6) == 1.064375
    assert round(calc.max_drawdown(path).drawdown, 6) == -0.025398

    historical = calc.historical_var(returns, confidence=0.95, portfolio_value=100_000.0)
    parametric = calc.parametric_var(returns, confidence=0.95, portfolio_value=100_000.0)
    shortfall = calc.expected_shortfall(returns, confidence=0.95, portfolio_value=100_000.0)

    assert round(historical, 2) == 1555.21
    assert round(parametric, 2) == 2084.04
    assert round(shortfall, 2) == 1555.21
