/**
 * Named aliases over the generated OpenAPI types.
 *
 * `schema.d.ts` is generated by `npm run api:types` from the backend's own
 * `/openapi.json`. Never hand-edit it, and never hand-write a shape here that
 * the backend does not actually return — a contract change must break the
 * build, not production. See AGENTS.md section 2.
 */

import type { components } from "./schema";

type Schemas = components["schemas"];

/* --- Auth ----------------------------------------------------------------- */
export type TokenResponse = Schemas["TokenResponse"];
export type UserResponse = Schemas["UserResponse"];
export type LoginRequest = Schemas["LoginRequest"];
export type RegisterRequest = Schemas["RegisterRequest"];

/* --- Portfolios ----------------------------------------------------------- */
export type PortfolioResponse = Schemas["PortfolioResponse"];
export type PortfolioSummaryResponse = Schemas["PortfolioSummaryResponse"];
export type PositionResponse = Schemas["PositionResponse"];

/* --- Analytics ------------------------------------------------------------ */
export type AnalysisRunResponse = Schemas["AnalysisRunResponse"];
export type AnalysisRunSummary = Schemas["AnalysisRunSummary"];

/* --- Stress testing ------------------------------------------------------- */
export type StressTestRunResponse = Schemas["StressTestRunResponse"];

/* --- Gjallarhorn ---------------------------------------------------------- */
export type AlertRuleResponse = Schemas["AlertRuleResponse"];
export type WarningSignalResponse = Schemas["WarningSignalResponse"];
export type SignalSummaryResponse = Schemas["SignalSummaryResponse"];
export type MonitoringRunResponse = Schemas["MonitoringRunResponse"];

/* --- Reports -------------------------------------------------------------- */
export type ReportResponse = Schemas["ReportResponse"];
